In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('call_activity.csv')
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [4]:
type(df)

pandas.core.frame.DataFrame

In [5]:
df['State']

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [7]:
type(df['State'])

pandas.core.series.Series

In [3]:
df.head()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

## Create a DataFrame from a Dictionary

In [8]:
tempDict={
    'Name':["John","Mike","Robert"],
    'Designation':['Software Engineer','Video Editor','Accountant'],
    'Salary':[10000,20000,30000]
}

In [9]:
dictDf = pd.DataFrame.from_dict(tempDict)

In [10]:
dictDf

     Name        Designation  Salary
0    John  Software Engineer   10000
1    Mike       Video Editor   20000
2  Robert         Accountant   30000

In [11]:
type(df.columns)

pandas.core.indexes.base.Index

In [12]:
df.dtypes

State                      object
Account length              int64
Area code                   int64
International plan         object
Voice mail plan            object
Number vmail messages       int64
Total day minutes         float64
Total day calls           float64
Total day charge          float64
Total eve minutes         float64
Total eve calls           float64
Total eve charge          float64
Total night minutes       float64
Total night calls         float64
Total night charge        float64
Total intl minutes        float64
Total intl calls            int64
Total intl charge         float64
Customer service calls    float64
Churn                      object
dtype: object

In [13]:
df.State

0       KS
1       OH
2       NJ
3       OH
4       OK
        ..
3328    AZ
3329    WV
3330    RI
3331    CT
3332    TN
Name: State, Length: 3333, dtype: object

In [15]:
df.State.unique()

array(['KS', 'OH', 'NJ', 'OK', 'AL', 'MA', 'MO', 'LA', 'WV', 'IN', 'RI',
       'IA', 'MT', 'NY', 'ID', 'VT', 'VA', 'TX', 'FL', 'CO', 'AZ', 'SC',
       'NE', 'WY', 'HI', 'IL', 'NH', 'GA', 'AK', 'MD', 'AR', 'WI', 'OR',
       'MI', 'DE', 'UT', 'CA', 'MN', 'SD', 'NC', 'WA', 'NM', 'NV', 'DC',
       'KY', 'ME', 'MS', 'TN', 'PA', 'CT', 'ND'], dtype=object)

In [18]:
df[df['International plan']=='Yes']

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
5,AL,118,510,Yes,No,0,223.4,98.0,37.98,220.6,101.0,18.75,203.9,118.0,9.18,6.3,6,1.70,0.0,False
7,MO,147,415,Yes,No,0,157.0,79.0,26.69,103.1,94.0,8.76,211.8,96.0,9.53,7.1,6,1.92,0.0,False
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3304,IL,71,510,Yes,No,0,186.1,114.0,31.64,198.6,140.0,16.88,206.5,80.0,9.29,13.8,5,3.73,4.0,True
3309,VT,100,408,Yes,No,0,219.4,112.0,37.30,225.7,102.0,19.18,255.3,95.0,11.49,12.0,4,3.24,4.0,False
3317,SD,163,415,Yes,No,0,197.2,90.0,33.52,188.5,113.0,16.02,211.1,94.0,9.50,7.8,8,2.11,1.0,False
3320,GA,122,510,Yes,No,0,140.0,101.0,23.80,196.4,77.0,16.69,120.1,133.0,5.40,9.7,4,2.62,4.0,True
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False

In [19]:
df[(df['International plan']=='Yes') & (df['Churn']==True)]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
41,MD,135,408,Yes,Yes,41,173.1,85.0,29.43,203.9,107.0,17.33,122.2,78.0,5.50,14.6,15,3.94,0.0,True
115,ME,36,510,Yes,Yes,42,196.8,89.0,33.46,254.9,122.0,21.67,138.3,126.0,6.22,20.0,6,5.40,0.0,True
144,VT,117,408,Yes,No,0,167.1,86.0,28.41,177.5,87.0,15.09,249.4,132.0,11.22,14.1,7,3.81,2.0,True
198,ME,131,510,Yes,Yes,26,292.9,101.0,49.79,199.7,97.0,16.97,255.3,127.0,11.49,13.8,7,3.73,4.0,True
214,FL,70,510,Yes,No,0,226.7,98.0,38.54,228.1,115.0,19.39,73.2,93.0,3.29,17.6,4,4.75,2.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3246,NC,77,408,Yes,Yes,44,103.2,117.0,17.54,236.3,86.0,20.09,203.5,101.0,9.16,11.9,2,3.21,0.0,True
3255,RI,138,510,Yes,No,0,286.2,61.0,48.65,187.2,60.0,15.91,146.2,114.0,6.58,11.0,4,2.97,2.0,True
3291,MI,119,510,Yes,Yes,22,172.1,119.0,29.26,223.6,133.0,19.01,150.0,94.0,6.75,13.9,20,3.75,1.0,True
3304,IL,71,510,Yes,No,0,186.1,114.0,31.64,198.6,140.0,16.88,206.5,80.0,9.29,13.8,5,3.73,4.0,True
3320,GA,122,510,Yes,No,0,140.0,101.0,23.80,196.4,77.0,16.69,120.1,133.0,5.40,9.7,4,2.62,4.0,True

In [20]:
df[(df['International plan']=='Yes') & (df['Total day charge']>31)]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
5,AL,118,510,Yes,No,0,223.4,98.0,37.98,220.6,101.0,18.75,203.9,118.0,9.18,6.3,6,1.70,0.0,False
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False
66,WY,43,415,Yes,No,0,251.5,105.0,42.76,212.8,104.0,18.09,157.8,67.0,7.10,9.3,4,2.51,0.0,False
81,OR,116,415,Yes,No,0,215.4,104.0,36.62,204.8,79.0,17.41,278.5,109.0,12.53,12.6,5,3.40,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3269,WV,117,510,Yes,No,0,198.4,121.0,33.73,249.5,104.0,21.21,162.8,115.0,7.33,10.5,5,2.84,1.0,False
3304,IL,71,510,Yes,No,0,186.1,114.0,31.64,198.6,140.0,16.88,206.5,80.0,9.29,13.8,5,3.73,4.0,True
3309,VT,100,408,Yes,No,0,219.4,112.0,37.30,225.7,102.0,19.18,255.3,95.0,11.49,12.0,4,3.24,4.0,False
3317,SD,163,415,Yes,No,0,197.2,90.0,33.52,188.5,113.0,16.02,211.1,94.0,9.50,7.8,8,2.11,1.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False

In [22]:
df.iloc[9]

State                        WV
Account length              141
Area code                   415
International plan          Yes
Voice mail plan             Yes
Number vmail messages        37
Total day minutes         258.6
Total day calls            84.0
Total day charge          43.96
Total eve minutes         222.0
Total eve calls           111.0
Total eve charge          18.87
Total night minutes       326.4
Total night calls          97.0
Total night charge        14.69
Total intl minutes         11.2
Total intl calls              5
Total intl charge          3.02
Customer service calls      0.0
Churn                     False
Name: 9, dtype: object

In [23]:
df.iloc[9,2]

np.int64(415)

In [24]:
df.iloc[3:10]

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
5,AL,118,510,Yes,No,0,223.4,98.0,37.98,220.6,101.0,18.75,203.9,118.0,9.18,6.3,6,1.70,0.0,False
6,MA,121,510,No,Yes,24,218.2,88.0,37.09,348.5,108.0,29.62,212.6,118.0,9.57,7.5,7,2.03,3.0,NaN
7,MO,147,415,Yes,No,0,157.0,79.0,26.69,103.1,94.0,8.76,211.8,96.0,9.53,7.1,6,1.92,0.0,False
8,LA,117,408,No,No,0,184.5,97.0,31.37,351.6,80.0,29.89,215.8,90.0,9.71,8.7,4,2.35,1.0,False
9,WV,141,415,Yes,Yes,37,258.6,84.0,43.96,222.0,111.0,18.87,326.4,97.0,14.69,11.2,5,3.02,0.0,False

In [26]:
state=df.copy()
state.set_index('State',inplace=True)

In [27]:
state.head()

,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
State,,,,,,,,,,,,,,,,,,,
KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False

In [28]:
state.loc['NJ']

,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
State,,,,,,,,,,,,,,,,,,,
NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
NJ,149,408,No,No,0,140.4,94.0,23.87,271.8,92.0,23.10,188.3,108.0,8.47,11.1,9,3.00,1.0,False
NJ,138,408,No,No,0,241.8,93.0,41.11,170.5,83.0,14.49,295.3,104.0,13.29,11.8,7,3.19,3.0,False
NJ,128,415,No,No,0,237.9,125.0,40.44,247.6,93.0,21.05,208.9,68.0,9.40,13.9,4,3.75,1.0,True
NJ,64,510,No,No,0,162.6,83.0,27.64,152.3,109.0,12.95,57.5,122.0,2.59,14.2,3,3.83,1.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
NJ,75,415,No,Yes,42,248.9,93.0,42.31,170.8,108.0,14.52,104.5,91.0,4.70,11.2,8,3.02,1.0,False
NJ,108,415,No,No,0,239.3,102.0,40.68,223.4,127.0,18.99,251.4,104.0,11.31,10.6,6,2.86,0.0,False
NJ,107,408,No,Yes,36,96.3,83.0,16.37,179.6,91.0,15.27,166.3,121.0,7.48,10.3,2,2.78,1.0,False
NJ,93,415,No,No,0,146.3,85.0,24.87,216.6,95.0,18.41,233.0,82.0,10.49,11.5,3,3.11,0.0,False
NJ,139,415,No,Yes,43,231.0,85.0,39.27,222.3,82.0,18.90,148.0,105.0,6.66,8.3,5,2.24,2.0,False

In [29]:
state.reset_index()

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False

In [30]:
df.isnull().sum()

State                      0
Account length             0
Area code                  0
International plan         0
Voice mail plan            0
Number vmail messages      0
Total day minutes         10
Total day calls           10
Total day charge          18
Total eve minutes          9
Total eve calls            8
Total eve charge           0
Total night minutes        0
Total night calls          1
Total night charge         0
Total intl minutes         0
Total intl calls           0
Total intl charge          5
Customer service calls     5
Churn                      8
dtype: int64

In [32]:
df.dropna(inplace=True)

In [33]:
df.isnull().sum()

State                     0
Account length            0
Area code                 0
International plan        0
Voice mail plan           0
Number vmail messages     0
Total day minutes         0
Total day calls           0
Total day charge          0
Total eve minutes         0
Total eve calls           0
Total eve charge          0
Total night minutes       0
Total night calls         0
Total night charge        0
Total intl minutes        0
Total intl calls          0
Total intl charge         0
Customer service calls    0
Churn                     0
dtype: int64

In [34]:
df.drop('Total night minutes',axis=1)

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,Total eve calls,Total eve charge,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,99.0,16.78,91.0,11.01,10.0,3,2.70,1.0,False
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,103.0,16.62,103.0,11.45,13.7,3,3.70,1.0,False
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,110.0,10.30,104.0,7.32,12.2,5,3.29,0.0,False
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,88.0,5.26,89.0,8.86,6.6,7,1.78,2.0,False
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,122.0,12.61,121.0,8.41,10.1,3,2.73,3.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,126.0,18.32,83.0,12.56,9.9,6,2.67,2.0,False
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,55.0,13.04,123.0,8.61,9.6,4,2.59,3.0,False
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,58.0,24.55,91.0,8.64,14.1,6,3.81,2.0,False
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,84.0,13.57,137.0,6.26,5.0,10,1.35,2.0,False
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,82.0,22.60,77.0,10.86,13.7,4,3.70,0.0,False

In [35]:
df['New Column']=df['Total day charge']+df['Total eve charge']

In [36]:
df

,State,Account length,Area code,International plan,Voice mail plan,Number vmail messages,Total day minutes,Total day calls,Total day charge,Total eve minutes,...,Total eve charge,Total night minutes,Total night calls,Total night charge,Total intl minutes,Total intl calls,Total intl charge,Customer service calls,Churn,New Column
0,KS,128,415,No,Yes,25,265.1,110.0,45.07,197.4,...,16.78,244.7,91.0,11.01,10.0,3,2.70,1.0,False,61.85
1,OH,107,415,No,Yes,26,161.6,123.0,27.47,195.5,...,16.62,254.4,103.0,11.45,13.7,3,3.70,1.0,False,44.09
2,NJ,137,415,No,No,0,243.4,114.0,41.38,121.2,...,10.30,162.6,104.0,7.32,12.2,5,3.29,0.0,False,51.68
3,OH,84,408,Yes,No,0,299.4,71.0,50.90,61.9,...,5.26,196.9,89.0,8.86,6.6,7,1.78,2.0,False,56.16
4,OK,75,415,Yes,No,0,166.7,113.0,28.34,148.3,...,12.61,186.9,121.0,8.41,10.1,3,2.73,3.0,False,40.95
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3328,AZ,192,415,No,Yes,36,156.2,77.0,26.55,215.5,...,18.32,279.1,83.0,12.56,9.9,6,2.67,2.0,False,44.87
3329,WV,68,415,No,No,0,231.1,57.0,39.29,153.4,...,13.04,191.3,123.0,8.61,9.6,4,2.59,3.0,False,52.33
3330,RI,28,510,No,No,0,180.8,109.0,30.74,288.8,...,24.55,191.9,91.0,8.64,14.1,6,3.81,2.0,False,55.29
3331,CT,184,510,Yes,No,0,213.8,105.0,36.35,159.6,...,13.57,139.2,137.0,6.26,5.0,10,1.35,2.0,False,49.92
3332,TN,74,415,No,Yes,25,234.4,113.0,39.85,265.9,...,22.60,241.4,77.0,10.86,13.7,4,3.70,0.0,False,62.45

In [37]:
df.iloc[1,1]

np.int64(107)

In [38]:
df.to_csv('output.csv')

In [39]:
dictDf.to_json()

'{"Name":{"0":"John","1":"Mike","2":"Robert"},"Designation":{"0":"Software Engineer","1":"Video Editor","2":"Accountant"},"Salary":{"0":10000,"1":20000,"2":30000}}'